import React, { useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';
import { modalVariants } from '../utils/animations';
import { logger } from '../utils/logger';

interface ImprintModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ImprintModal: React.FC<ImprintModalProps> = ({ isOpen, onClose }) => {
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        logger.debug('Modal closed via Escape key');
        onClose();
      }
    };

    if (isOpen) {
      logger.info('Modal opened');
      document.addEventListener('keydown', handleEscape);
      document.body.style.overflow = 'hidden';
    }

    return () => {
      if (isOpen) {
        logger.info('Modal closed');
      }
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = 'unset';
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const handleBackdropClick = () => {
    logger.debug('Modal closed via backdrop click');
    onClose();
  };

  const handleCloseButtonClick = () => {
    logger.debug('Modal closed via close button');
    onClose();
  };

  return (
    <div
      className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50"
      onClick={handleBackdropClick}
      data-testid="modal-backdrop"
    >
      <AnimatePresence>
        <motion.div
          variants={modalVariants}
          initial="hidden"
          animate="visible"
          exit="exit"
          className="bg-white/10 backdrop-blur-md rounded-xl p-6 max-w-lg w-full shadow-xl"
          onClick={e => e.stopPropagation()}
        >
          <div className="flex justify-between items-start mb-4">
            <h2 className="text-2xl font-bold">Legal Notice</h2>
            <button
              onClick={handleCloseButtonClick}
              className="p-1 hover:bg-white/10 rounded-lg transition-colors"
            >
              <X size={24} />
            </button>
          </div>

          <div className="space-y-4 text-white/80">
            <p>
              <strong>Retreat Roulette</strong> is a fun project created for entertainment purposes only.
              The generated retreat combinations are randomly created and not affiliated with any actual retreats or organizations.
            </p>

            <p>
              <strong>Contact:</strong><br />
              Email: hello@retreat-roulette.com<br />
              Website: https://retreat-roulette.com
            </p>

            <p>
              <strong>Disclaimer:</strong><br />
              The content generated by this website is purely fictional and for entertainment purposes.
              Any resemblance to actual retreats, events, or organizations is purely coincidental.
            </p>

            <p>
              <strong>Privacy:</strong><br />
              We use local storage to save your favorite combinations.
              No personal data is collected or stored on our servers.
            </p>
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}; 